export const realisations = [
  {
    nom: 'Château des Lumières',
    type: 'Site vitrine — Hôtel boutique',
    projectType: 'demo' as const,
    slug: 'chateau-lumieres',
    url: 'https://stackup-demos-e85v.vercel.app',
    couleur: '#213547',
    accent: '#5F8D6A',
    description: "Expérience immersive de visite virtuelle de l'hôtel avec réservation de chambres et de soins spa.",
    tags: ['Site vitrine', 'Réservation', 'Spa', 'Événements'],
    services: ['Développement web', 'Design UI/UX', 'Animations avancées'],
    fonctionnalites: [
      'Visite guidée immersive pièce par pièce',
      'Calendrier de disponibilité des chambres',
      'Réservation de soins spa en ligne',
      'Section événements (mariages, séminaires)',
      "Ambiance lumineuse adaptée à l'heure réelle",
      'Galerie photographique professionnelle',
      'Module d\'avis clients intégré (données de démonstration)',
      "Menu restaurant de l'hôtel",
      'Conciergerie en ligne',
      'Navigation par scroll cinématographique',
    ],
    filterType: 'Site vitrine',
  },
  {
    nom: 'Maison Élise',
    type: 'Site e-commerce — Boutique mode',
    projectType: 'demo' as const,
    slug: 'maison-elise',
    url: 'https://stackup-demos-tq9a.vercel.app',
    couleur: '#2E2B28',
    accent: '#D46A92',
    description: 'Boutique en ligne éditoriale avec catalogue filtrable, panier dynamique et expérience magazine.',
    tags: ['E-commerce', 'Mode', 'Panier', 'Catalogue'],
    services: ['E-commerce', 'Design éditorial', 'UX Shopping'],
    fonctionnalites: [
      'Catalogue produits avec filtres avancés',
      'Panier latéral animé slide-in',
      'Wishlist et favoris',
      'Guide des tailles interactif',
      'Lookbook éditorial pleine largeur',
      'Bannière promotionnelle animée',
      'Compte à rebours offres limitées',
      'Progress bar livraison gratuite',
      'Pop-up newsletter avec réduction',
      'Section best-sellers avec compteur',
    ],
    filterType: 'E-commerce',
  },
  {
    nom: 'Au Pain Doré',
    type: 'Site vitrine — Boulangerie artisanale',
    projectType: 'demo' as const,
    slug: 'au-pain-dore',
    url: 'https://stackup-demos-u2go.vercel.app',
    couleur: '#5A3E2B',
    accent: '#D89C4A',
    description: 'Site chaleureux avec click & collect, catalogue produits et statut ouvert/fermé en temps réel.',
    tags: ['Site vitrine', 'Click & Collect', 'Catalogue', 'Artisanal'],
    services: ['Développement web', 'Design chaleureux', 'Click & Collect'],
    fonctionnalites: [
      'Système Click & Collect avec créneaux de retrait',
      'Catalogue par catégorie (Pains/Viennoiseries/Pâtisseries)',
      'Produit du jour avec stock en temps réel',
      'Statut ouvert/fermé automatique selon les horaires',
      'Compte à rebours prochaine fournée',
      'Animation pain qui gonfle en CSS',
      'Abonnement panier hebdomadaire',
      'Notre histoire — timeline familiale',
      'Engagements qualité mis en avant',
      'Programme fidélité boulangerie',
    ],
    filterType: 'Site vitrine',
  },
  {
    nom: 'Prestige Immo',
    type: 'Site vitrine — Agence immobilière',
    projectType: 'demo' as const,
    slug: 'prestige-immo',
    url: 'https://stackup-demos-9lnu.vercel.app',
    couleur: '#17202A',
    accent: '#008C8C',
    description: 'Plateforme immobilière avec recherche avancée, simulateur de crédit et estimation en ligne.',
    tags: ['Site vitrine', 'Immobilier', 'Simulateur', 'Estimation'],
    services: ['Développement web', 'Design data-driven', 'Outils interactifs'],
    fonctionnalites: [
      'Moteur de recherche avec filtres avancés',
      'Fiches biens avec carousel photos',
      'DPE visuel coloré et interactif',
      'Simulateur de crédit en temps réel',
      'Estimateur de bien en ligne',
      'Alertes email nouveaux biens',
      'Carte interactive des biens',
      'Profils agents avec spécialités',
      'Statistiques marché local',
      'Comparateur de biens',
    ],
    filterType: 'Site vitrine',
  },
  {
    nom: "L'Olivier — Dashboard",
    type: 'Système de gestion — Restaurant',
    projectType: 'demo' as const,
    slug: 'lolivier-dashboard',
    url: 'https://stackup-demos-jxtr.vercel.app',
    couleur: '#101828',
    accent: '#29C36A',
    description: 'Interface de gestion complète pour restaurant : commandes, réservations, plan de salle et analytics.',
    tags: ['Système de gestion', 'Dashboard', 'Temps réel', 'Analytics'],
    services: ['Application web', 'Dashboard SaaS', 'Temps réel'],
    fonctionnalites: [
      'Dashboard KPIs avec données temps réel',
      'Plan de salle interactif cliquable',
      'Gestion des tickets cuisine',
      'Liste des réservations du jour',
      'Graphiques CA et statistiques',
      'Gestion du menu en ligne',
      'Planning et gestion du staff',
      'Programme fidélité clients',
      'Notifications en temps réel',
      'Export des données et rapports',
    ],
    filterType: 'Système de gestion',
  },
  {
    nom: 'Domaine Château Fleury',
    type: 'Site e-commerce — Cave à vins',
    projectType: 'demo' as const,
    slug: 'chateau-fleury',
    url: 'https://stackup-demos-9ib4.vercel.app',
    couleur: '#2F1B14',
    accent: '#7A1F2B',
    description: 'Boutique en ligne premium pour cave à vins avec catalogue filtrable et abonnements mensuels.',
    tags: ['E-commerce', 'Vins', 'Abonnement', 'Premium'],
    services: ['E-commerce', 'Design luxe', 'Abonnements'],
    fonctionnalites: [
      'Catalogue vins avec filtres (appellation/millésime/type)',
      'Fiches vins détaillées avec accords mets',
      'Coffrets cadeaux configurables',
      'Abonnement Cave du mois (3 formules)',
      'Rotation 3D des bouteilles au hover',
      'Guide des appellations interactif',
      'Réservation de dégustations',
      'Avis sommeliers intégrés',
      'Section presse et récompenses',
      'Click & Collect ou livraison',
    ],
    filterType: 'E-commerce',
  },
]
