export const realisations = [
  {
    nom: 'Cadence Studio',
    type: 'Site vitrine + espace de livraison — Vidéaste',
    projectType: 'demo' as const,
    slug: 'demo-videaste',
    image: '/images/realisations/demo-videaste.webp',
    url: 'https://demo-videaste-vitrine.vercel.app',
    couleur: '#0C1017',
    accent: '#E8B84B',
    description: "La vitrine complète de notre offre vidéaste : site portfolio cinématographique + espace de livraison client avec commentaires horodatés sur la timeline vidéo, versions de montage V1/V2/V3, liens privés par destinataire et espace de gestion. Entièrement visitable, accès admin inclus.",
    tags: ['Vidéaste', 'Livraison client', 'Timeline', 'Espace admin'],
    services: ['Développement web', 'Système de livraison vidéo', 'Design cinématographique'],
    fonctionnalites: [
      'Portfolio de films avec lecture immersive',
      'Espace de livraison client par lien privé',
      'Commentaires horodatés sur la timeline vidéo',
      'Versions de montage V1 / V2 / V3 comparables',
      'Liens privés par destinataire avec QR code',
      'Espace de gestion des projets et livraisons',
      'Suivi des validations par version',
      'Pages prestations (mariage, entreprise, clip)',
      'Formulaire de demande de projet qualifié',
      'Design sombre cinématographique sur mesure',
    ],
    filterType: 'Site vitrine',
    caseStudy: {
      contexte: "Un vidéaste indépendant vit deux métiers à la fois : convaincre les futurs clients avec un portfolio à la hauteur de ses films, et livrer les clients existants sans friction — versions successives, retours précis, validation finale. Les outils par abonnement (Vimeo Pro, WeTransfer, Frame.io) règlent ce second métier au prix d'une rente mensuelle, sur la marque d'un tiers. Cadence Studio démontre l'alternative : tout est intégré au site du vidéaste, acheté une fois, possédé pour toujours.",
      construit: [
        'Un site vitrine cinématographique : portfolio de films, prestations, tarifs, demande de projet',
        "Un espace de livraison client : chaque projet a son lien privé par destinataire (avec QR code), ses versions de montage V1/V2/V3, et des commentaires horodatés directement sur la timeline de la vidéo — le client clique à 1:24, écrit « couper ce plan », le vidéaste voit exactement où",
        "Un espace de gestion : création des projets, upload des versions, suivi des retours et des validations",
      ],
      tester: [
        "Parcourez le site public librement — portfolio, prestations, tarifs",
        "Ouvrez l'espace de livraison depuis le site et explorez un projet de démonstration : timeline, commentaires, versions",
        "Connectez-vous à l'espace de gestion avec l'accès admin ci-dessous et regardez l'envers du décor",
      ],
    },
    demoAccess: {
      password: 'demo2026',
      note: 'Démonstration complète — entreprise fictive, fonctionnalités réelles.',
    },
  },
  {
    nom: 'Château des Lumières',
    type: 'Site vitrine — Hôtel boutique',
    projectType: 'demo' as const,
    slug: 'chateau-lumieres',
    image: '/images/realisations/chateau-lumieres.webp',
    url: 'https://stackup-demos-e85v.vercel.app',
    couleur: '#213547',
    accent: '#5F8D6A',
    description: "Site hôtel boutique avec visite immersive room-by-room, réservation de chambres, soins spa en ligne et galerie photographique professionnelle.",
    tags: ['Site vitrine', 'Réservation', 'Spa', 'Événements'],
    services: ['Développement web', 'Design UI/UX', 'Animations avancées'],
    fonctionnalites: [
      'Visite guidée immersive pièce par pièce',
      'Calendrier de disponibilité des chambres',
      'Réservation de soins spa en ligne',
      'Section événements (mariages, séminaires)',
      "Ambiance lumineuse adaptée à l'heure réelle",
      'Galerie photographique professionnelle',
      'Module d\'avis clients intégré (données de démonstration)',
      "Menu restaurant de l'hôtel",
      'Conciergerie en ligne',
      'Navigation par scroll cinématographique',
    ],
    filterType: 'Site vitrine',
  },
  {
    nom: 'Maison Élise',
    type: 'Site e-commerce — Boutique mode',
    projectType: 'demo' as const,
    slug: 'maison-elise',
    image: '/images/realisations/maison-elise.webp',
    url: 'https://stackup-demos-tq9a.vercel.app',
    couleur: '#2E2B28',
    accent: '#D46A92',
    description: 'Boutique mode e-commerce avec catalogue filtrable, panier latéral animé, wishlist, lookbook éditorial et guide des tailles interactif.',
    tags: ['E-commerce', 'Mode', 'Panier', 'Catalogue'],
    services: ['E-commerce', 'Design éditorial', 'UX Shopping'],
    fonctionnalites: [
      'Catalogue produits avec filtres avancés',
      'Panier latéral animé slide-in',
      'Wishlist et favoris',
      'Guide des tailles interactif',
      'Lookbook éditorial pleine largeur',
      'Bannière promotionnelle animée',
      'Compte à rebours offres limitées',
      'Progress bar livraison gratuite',
      'Pop-up newsletter avec réduction',
      'Section best-sellers avec compteur',
    ],
    filterType: 'E-commerce',
  },
  {
    nom: 'Au Pain Doré',
    type: 'Site vitrine — Boulangerie artisanale',
    projectType: 'demo' as const,
    slug: 'au-pain-dore',
    image: '/images/realisations/au-pain-dore.webp',
    url: 'https://stackup-demos-u2go.vercel.app',
    couleur: '#5A3E2B',
    accent: '#D89C4A',
    description: 'Site boulangerie artisanale avec click & collect, catalogue par catégorie, statut ouvert/fermé automatique et programme de fidélité.',
    tags: ['Site vitrine', 'Click & Collect', 'Catalogue', 'Artisanal'],
    services: ['Développement web', 'Design chaleureux', 'Click & Collect'],
    fonctionnalites: [
      'Système Click & Collect avec créneaux de retrait',
      'Catalogue par catégorie (Pains/Viennoiseries/Pâtisseries)',
      'Produit du jour avec stock en temps réel',
      'Statut ouvert/fermé automatique selon les horaires',
      'Compte à rebours prochaine fournée',
      'Animation pain qui gonfle en CSS',
      'Abonnement panier hebdomadaire',
      'Notre histoire — timeline familiale',
      'Engagements qualité mis en avant',
      'Programme fidélité boulangerie',
    ],
    filterType: 'Site vitrine',
  },
  {
    nom: 'Prestige Immo',
    type: 'Site vitrine — Agence immobilière',
    projectType: 'demo' as const,
    slug: 'prestige-immo',
    image: '/images/realisations/prestige-immo.webp',
    url: 'https://stackup-demos-9lnu.vercel.app',
    couleur: '#17202A',
    accent: '#008C8C',
    description: 'Plateforme immobilière avec moteur de recherche avancé, fiches biens, DPE visuel, simulateur de crédit et estimateur de bien en ligne.',
    tags: ['Site vitrine', 'Immobilier', 'Simulateur', 'Estimation'],
    services: ['Développement web', 'Design data-driven', 'Outils interactifs'],
    fonctionnalites: [
      'Moteur de recherche avec filtres avancés',
      'Fiches biens avec carousel photos',
      'DPE visuel coloré et interactif',
      'Simulateur de crédit en temps réel',
      'Estimateur de bien en ligne',
      'Alertes email nouveaux biens',
      'Carte interactive des biens',
      'Profils agents avec spécialités',
      'Statistiques marché local',
      'Comparateur de biens',
    ],
    filterType: 'Site vitrine',
  },
  {
    nom: "L'Olivier — Dashboard",
    type: 'Système de gestion — Restaurant',
    projectType: 'demo' as const,
    slug: 'lolivier-dashboard',
    image: '/images/realisations/lolivier-dashboard.webp',
    url: 'https://stackup-demos-jxtr.vercel.app',
    couleur: '#101828',
    accent: '#29C36A',
    description: 'Application de gestion restaurant avec dashboard temps réel, plan de salle interactif, tickets cuisine, analytics et programme fidélité clients.',
    tags: ['Système de gestion', 'Dashboard', 'Temps réel', 'Analytics'],
    services: ['Application web', 'Dashboard SaaS', 'Temps réel'],
    fonctionnalites: [
      'Dashboard KPIs avec données temps réel',
      'Plan de salle interactif cliquable',
      'Gestion des tickets cuisine',
      'Liste des réservations du jour',
      'Graphiques CA et statistiques',
      'Gestion du menu en ligne',
      'Planning et gestion du staff',
      'Programme fidélité clients',
      'Notifications en temps réel',
      'Export des données et rapports',
    ],
    filterType: 'Système de gestion',
  },
  {
    nom: 'Domaine Château Fleury',
    type: 'Site e-commerce — Cave à vins',
    projectType: 'demo' as const,
    slug: 'chateau-fleury',
    image: '/images/realisations/chateau-fleury.webp',
    url: 'https://stackup-demos-9ib4.vercel.app',
    couleur: '#2F1B14',
    accent: '#7A1F2B',
    description: 'Boutique en ligne cave à vins avec catalogue filtrable, fiches vins détaillées avec accords mets, coffrets cadeaux et abonnements mensuels.',
    tags: ['E-commerce', 'Vins', 'Abonnement', 'Premium'],
    services: ['E-commerce', 'Design luxe', 'Abonnements'],
    fonctionnalites: [
      'Catalogue vins avec filtres (appellation/millésime/type)',
      'Fiches vins détaillées avec accords mets',
      'Coffrets cadeaux configurables',
      'Abonnement Cave du mois (3 formules)',
      'Rotation 3D des bouteilles au hover',
      'Guide des appellations interactif',
      'Réservation de dégustations',
      'Avis sommeliers intégrés',
      'Section presse et récompenses',
      'Click & Collect ou livraison',
    ],
    filterType: 'E-commerce',
  },
]
