/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
  },
  compress: true,
  poweredByHeader: false,
  redirects: async () => [
    {
      source: '/:path*',
      has: [{ type: 'host', value: 'www.stackup-agency.fr' }],
      destination: 'https://stackup-agency.fr/:path*',
      permanent: true,
    },
    {
      source: '/en',
      destination: '/',
      permanent: true,
    },
    {
      source: '/blog/pourquoi-votre-restaurant-a-besoin-dun-site-web-en-2026',
      destination: '/blog/pourquoi-votre-restaurant-perd-des-clients-sans-site-web',
      permanent: true,
    },
    {
      source: '/blog/avis-clients-google-strategie',
      destination: '/blog/avis-google-strategie-complete',
      permanent: true,
    },
    {
      source: '/blog/hebergement-web-comment-choisir',
      destination: '/blog/hebergement-web-choisir',
      permanent: true,
    },
    {
      source: '/blog/seo-local-google-maps-premier',
      destination: '/blog/seo-local-google-maps-2026',
      permanent: true,
    },
    {
      // Phase 5 (volet B) : fusion de deux articles quasi-doublons sur la même requête
      source: '/blog/seo-local-artisan',
      destination: '/blog/seo-local-artisan-batiment-2026',
      permanent: true,
    },
    // Phase 3: migration articles ville -> /agence-web/[ville]
    { source: '/blog/agence-web-amboise', destination: '/agence-web/amboise', permanent: true },
    { source: '/blog/agence-web-anet', destination: '/agence-web/anet', permanent: true },
    { source: '/blog/agence-web-angers', destination: '/agence-web/angers', permanent: true },
    { source: '/blog/agence-web-blois', destination: '/agence-web/blois', permanent: true },
    { source: '/blog/agence-web-caen', destination: '/agence-web/caen', permanent: true },
    { source: '/blog/agence-web-chateaudun', destination: '/agence-web/chateaudun', permanent: true },
    { source: '/blog/agence-web-chinon', destination: '/agence-web/chinon', permanent: true },
    { source: '/blog/agence-web-evreux', destination: '/agence-web/evreux', permanent: true },
    { source: '/blog/agence-web-le-mans', destination: '/agence-web/le-mans', permanent: true },
    { source: '/blog/agence-web-nantes', destination: '/agence-web/nantes', permanent: true },
    { source: '/blog/agence-web-nogent-le-rotrou', destination: '/agence-web/nogent-le-rotrou', permanent: true },
    { source: '/blog/agence-web-rambouillet', destination: '/agence-web/rambouillet', permanent: true },
    { source: '/blog/agence-web-rouen', destination: '/agence-web/rouen', permanent: true },
    { source: '/blog/agence-web-saumur', destination: '/agence-web/saumur', permanent: true },
    { source: '/blog/agence-web-vendome', destination: '/agence-web/vendome', permanent: true },
    { source: '/blog/agence-web-vernouillet', destination: '/agence-web/vernouillet', permanent: true },
    { source: '/blog/seo-local-chartres', destination: '/agence-web/chartres', permanent: true },
    { source: '/blog/seo-local-dreux', destination: '/agence-web/dreux', permanent: true },
    { source: '/blog/seo-local-orleans', destination: '/agence-web/orleans', permanent: true },
    { source: '/blog/seo-local-tours', destination: '/agence-web/tours', permanent: true },
    // Phase 3: migration articles métier -> /creation-site-internet/[metier]
    { source: '/blog/site-web-auto-ecole-reservation', destination: '/creation-site-internet/auto-ecole', permanent: true },
    { source: '/blog/site-web-avocat-expert-comptable', destination: '/creation-site-internet/avocat', permanent: true },
    { source: '/blog/site-web-bijouterie-horlogerie', destination: '/creation-site-internet/bijouterie-horlogerie', permanent: true },
    { source: '/blog/site-web-boulangerie-patisserie', destination: '/creation-site-internet/boulangerie-patisserie', permanent: true },
    { source: '/blog/site-web-brasserie-bar', destination: '/creation-site-internet/brasserie-bar', permanent: true },
    { source: '/blog/site-web-cabinet-medical-kine', destination: '/creation-site-internet/cabinet-medical', permanent: true },
    { source: '/blog/site-web-cafe-salon-the', destination: '/creation-site-internet/cafe-salon-the', permanent: true },
    { source: '/blog/site-web-carreleur-sol', destination: '/creation-site-internet/carreleur-sol', permanent: true },
    { source: '/blog/site-web-cave-vins-spiritueux', destination: '/creation-site-internet/cave-vins-spiritueux', permanent: true },
    { source: '/blog/site-web-chauffagiste-climatisation', destination: '/creation-site-internet/chauffagiste-climatisation', permanent: true },
    { source: '/blog/site-web-cosmetiques-naturels', destination: '/creation-site-internet/cosmetiques-naturels', permanent: true },
    { source: '/blog/site-web-couvreur-charpentier', destination: '/creation-site-internet/couvreur-charpentier', permanent: true },
    { source: '/blog/site-web-electricien', destination: '/creation-site-internet/electricien', permanent: true },
    { source: '/blog/site-web-epicerie-fine', destination: '/creation-site-internet/epicerie-fine', permanent: true },
    { source: '/blog/site-web-fleuriste-vente-en-ligne', destination: '/creation-site-internet/fleuriste', permanent: true },
    { source: '/blog/site-web-food-truck', destination: '/creation-site-internet/food-truck', permanent: true },
    { source: '/blog/site-web-hotel-chambres-hotes', destination: '/creation-site-internet/hotel-chambres-hotes', permanent: true },
    { source: '/blog/site-web-informatique-telephonie', destination: '/creation-site-internet/magasin-informatique', permanent: true },
    { source: '/blog/site-web-jardinerie-animalerie', destination: '/creation-site-internet/jardinerie-animalerie', permanent: true },
    { source: '/blog/site-web-jouets-loisirs-creatifs', destination: '/creation-site-internet/magasin-jouets', permanent: true },
    { source: '/blog/site-web-kebab-fast-food', destination: '/creation-site-internet/kebab-fast-food', permanent: true },
    { source: '/blog/site-web-librairie-independante', destination: '/creation-site-internet/librairie-papeterie', permanent: true },
    { source: '/blog/site-web-librairie-papeterie', destination: '/creation-site-internet/librairie-papeterie', permanent: true },
    { source: '/blog/site-web-macon-renovateur', destination: '/creation-site-internet/macon-renovateur', permanent: true },
    { source: '/blog/site-web-magasin-sport-loisirs', destination: '/creation-site-internet/magasin-sport', permanent: true },
    { source: '/blog/site-web-maison-decoration', destination: '/creation-site-internet/boutique-decoration', permanent: true },
    { source: '/blog/site-web-menuisier-ebeniste', destination: '/creation-site-internet/menuisier-ebeniste', permanent: true },
    { source: '/blog/site-web-optique-lunetterie', destination: '/creation-site-internet/opticien', permanent: true },
    { source: '/blog/site-web-paysagiste-jardinier', destination: '/creation-site-internet/paysagiste-jardinier', permanent: true },
    { source: '/blog/site-web-peintre-decorateur', destination: '/creation-site-internet/peintre-decorateur', permanent: true },
    { source: '/blog/site-web-pharmacie-parapharmacie', destination: '/creation-site-internet/pharmacie-parapharmacie', permanent: true },
    { source: '/blog/site-web-pizzeria', destination: '/creation-site-internet/pizzeria', permanent: true },
    { source: '/blog/site-web-plombier', destination: '/creation-site-internet/plombier', permanent: true },
    { source: '/blog/site-web-restaurant-gastronomique', destination: '/creation-site-internet/restaurant-gastronomique', permanent: true },
    { source: '/blog/site-web-salon-coiffure-esthetique', destination: '/creation-site-internet/salon-coiffure', permanent: true },
    { source: '/blog/site-web-serrurier-depannage', destination: '/creation-site-internet/serrurier-depannage', permanent: true },
    { source: '/blog/site-web-sport-outdoor', destination: '/creation-site-internet/magasin-sport', permanent: true },
    { source: '/blog/site-web-tabac-presse', destination: '/creation-site-internet/tabac-presse', permanent: true },
    { source: '/blog/site-web-traiteur-evenementiel', destination: '/creation-site-internet/traiteur-evenementiel', permanent: true },
    { source: '/blog/site-web-vetements-enfants', destination: '/creation-site-internet/vetements-enfants', permanent: true },
    { source: '/ressources/modele-devis', destination: '/ressources/documents', permanent: true },
    { source: '/ressources/modele-facture', destination: '/ressources/documents', permanent: true },
    { source: '/motion-lab', destination: '/', permanent: true },
  ],
  headers: async () => [
    {
      source: '/(.*)',
      headers: [
        { key: 'X-Content-Type-Options', value: 'nosniff' },
        { key: 'X-Frame-Options', value: 'DENY' },
        { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
      ],
    },
    {
      source: '/documents/:path*',
      headers: [{ key: 'X-Robots-Tag', value: 'noindex, nofollow' }],
    },
    {
      source: '/(.*)\\.(jpg|jpeg|png|gif|ico|svg|webp|avif|woff|woff2)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
    },
  ],
}

export default nextConfig
