export const SITE = {
  name: 'Stackup Agency',
  legalName: 'Stackup Agency',
  url: 'https://stackup-agency.fr',
  email: 'contact@stackup-agency.fr',
  signature: "L'équipe Stackup Agency",
  address: {
    locality: 'Tours',
    department: 'Indre-et-Loire',
    departmentCode: '37',
    region: 'Centre-Val de Loire',
    country: 'FR',
  },
  serviceArea: 'Toute la France — interventions à distance et en région Centre-Val de Loire',
  founded: '2026',
  social: {
    linkedin: 'https://www.linkedin.com/in/stackup-agency-5756943aa/',
    instagram: 'https://www.instagram.com/stackup.agency/',
    facebook: 'https://www.facebook.com/profile.php?id=61588724591496',
  },
  pricing: {
    vitrine: 449,
    multipages: 749,
    association: 149,
    gestion: 1447,
    ecommerce: 1647,
    marketingMensuel: 299,
    redactionArticle: 25,
    maintenanceStarter: 29,
    maintenancePro: 44,
    maintenancePremium: 89,
  },
  delais: {
    vitrine: '10 jours ouvrés',
    multipages: '17 jours ouvrés',
    ecommerce: '21 jours ouvrés',
    gestion: '21 jours ouvrés',
    association: '7 jours ouvrés',
  },
  indexNowKey: 'a3f7c2e1d9b4e8f0a1c5d7e9f2b3a4c6',
} as const

/** Source unique des 7 offres affichées partout (cartes, tarifs, fiches) */
export const SERVICES = [
  {
    id: 'site-vitrine',
    titre: 'Site vitrine',
    prix: 449,
    unite: '€',
    delai: '10 jours ouvrés',
    desc: 'Présence professionnelle en ligne, SEO local, formulaire de contact. Hébergement 12 mois inclus.',
    href: '/services/site-vitrine',
    badge: 'Le plus rapide',
  },
  {
    id: 'site-multi-pages',
    titre: 'Site multi-pages',
    prix: 749,
    unite: '€',
    delai: '17 jours ouvrés',
    desc: 'Site complet avec blog, galerie, pages service, Google Analytics et formulaires avancés.',
    href: '/services/site-multi-pages',
    badge: null,
  },
  {
    id: 'site-ecommerce',
    titre: 'Boutique en ligne',
    prix: 1647,
    unite: '€',
    delai: '21 jours ouvrés',
    desc: 'E-commerce complet avec catalogue, paiement Stripe, gestion des stocks et tableau de bord.',
    href: '/services/site-ecommerce',
    badge: 'Le plus populaire',
  },
  {
    id: 'systeme-gestion',
    titre: 'Système de gestion',
    prix: 1447,
    unite: '€',
    delai: '21 jours ouvrés',
    desc: 'Logiciel sur mesure : caisse, agenda, CRM, commandes. Données hébergées en France.',
    href: '/services/systeme-gestion',
    badge: 'Sur mesure',
  },
  {
    id: 'site-association',
    titre: 'Site association',
    prix: 149,
    unite: '€',
    delai: '7 jours ouvrés',
    desc: 'Site loi 1901 avec adhésion en ligne, agenda des événements et formulaire de bénévolat.',
    href: '/services/site-association',
    badge: null,
  },
  {
    id: 'marketing-digital',
    titre: 'Marketing digital',
    prix: 299,
    unite: '€/mois',
    delai: null,
    desc: 'Stratégie SEO, Google Ads, réseaux sociaux et reporting mensuel pour booster votre visibilité.',
    href: '/services',
    badge: null,
  },
  {
    id: 'redaction-blog-seo',
    titre: 'Rédaction blog SEO',
    prix: 25,
    unite: '€/article',
    delai: null,
    desc: 'Articles optimisés SEO rédigés par des experts, publiés et maillés dans votre site.',
    href: '/services/redaction-blog-seo',
    badge: null,
  },
] as const
